name: Deploy Cloudflare Workers

on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploy to Cloudflare Workers
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Run Tests, Migrations and Deploy using Cloudflare CLI environment
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          preCommands: |
            pnpm test 
            pnpm migration:prod
      